version: "3"

services:
  mongo1:
    image: "bitnami/mongodb:4.4.2"
    env_file:
      - .env
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB1_HOSTNAME:-mongo1}
      - MONGODB_PORT_NUMBER=30001
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password123}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY:-replicasetkey}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-razrnodes}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-razrdbuser}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password123}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-razrdb}
      # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=4
    volumes:
      - "mongo1_data:/bitnami"
    networks:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica1 == 1

  mongo2:
    image: "bitnami/mongodb:4.4.2"
    env_file:
      - .env
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo1
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB2_HOSTNAME:-mongo2}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password123}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY:-replicasetkey}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-razrnodes}
      # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=4
    volumes:
      - "mongo2_data:/bitnami"
    networks:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica2 == 1

  mongo3:
    image: "bitnami/mongodb:4.4.2"
    env_file:
      - .env
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo1
      - MONGODB_PORT_NUMBER=30003
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB3_HOSTNAME:-mongo3}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password123}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY:-replicasetkey}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-razrnodes}
      # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=4
    volumes:
      - "mongo3_data:/bitnami"
    networks:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica3 == 1

  # mongo4:
  #   image: "bitnami/mongodb:4.4.2"
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_PRIMARY_HOST=mongo1
  #     - MONGODB_PORT_NUMBER=30004
  #     - MONGODB_PRIMARY_PORT_NUMBER=30001
  #     - MONGODB_ADVERTISED_HOSTNAME=${MONGODB4_HOSTNAME:-mongo4}
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD }
  #     - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY:-replicasetkey}
  #     - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-razrnodes}
  #     # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=4
  #   volumes:
  #     - "mongo4_data:/bitnami"
  #   networks:
  #     - mongo
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-file: "5"
  #       max-size: "500m"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.mongo.replica4 == 1

  # mongo5:
  #   image: "bitnami/mongodb:4.4.2"
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_PRIMARY_HOST=mongo5
  #     - MONGODB_PORT_NUMBER=30005
  #     - MONGODB_PRIMARY_PORT_NUMBER=30001
  #     - MONGODB_ADVERTISED_HOSTNAME=${MONGODB4_HOSTNAME:-mongo5}
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
  #     - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY:-replicasetkey}
  #     - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-razrnodes}
  #     # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=4
  #   volumes:
  #     - "mongo5_data:/bitnami"
  #   networks:
  #     - mongo
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-file: "5"
  #       max-size: "500m"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.mongo.replica4 == 1

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  # mongo4_data:
  # mongo5_data:

networks:
  mongo:
