version: "2"

services:
  mongo2:
    image: "bitnami/mongodb:4.4.2"
    container_name: "mongo2"
    ports:
      - "30002:30002"
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo1
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB2_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "./data/mongo2:/bitnami"
    networks:
      - "ingress"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

networks:
  ingress:
    external: true
