version: "2"

services:
  mongo3:
    image: "bitnami/mongodb:4.4.2"
    container_name: "mongo3"
    ports:
      - "30003:30003"
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo1
      - MONGODB_PORT_NUMBER=30003
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB3_HOSTNAME}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
    volumes:
      - "./data/mongo3:/bitnami"
    networks:
      - "razr-overlay"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

networks:
  razr-overlay:
    external: true
