version: "2.4"

services:
  mongo1:
    image: "bitnami/mongodb:4.4.2"
    container_name: "mongo1"
    ports:
      - "30001:30001"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB1_HOSTNAME}
      - MONGODB_PORT_NUMBER=30001
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - "./data/mongo1:/bitnami"
    networks:
      - "razr-overlay"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

networks:
  razr-overlay:
    external: true
